$axure.loadCurrentPage({
  "url":"其它.html",
  "generationDate":new Date(1432187596355.73),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b40db783534f4ead910bbb51fcadea9b",
    "type":"Axure:Page",
    "name":"其它",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ce6386ad57484fa2812bca34fe8a84de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":130,
              "y":108},
            "size":{
              "width":80,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcd9643eb2f149628ab8c6667f71cc48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":130,
                  "y":108},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c21cc933d4b49b8bc794d03036cde81",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"right",
            "location":{
              "x":134,
              "y":152},
            "size":{
              "width":140,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c941ecc5fe064f27863f630449f18796",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"right",
                "location":{
                  "x":134,
                  "y":152},
                "size":{
                  "width":140,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96ec17f3a98946e687772b5828ff288f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":390,
              "y":593},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 求职报名表 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"求职报名表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "annotation":{
            "描述":"点击提交按钮，弹出提示框，确认要提交吗"}},
{
          "id":"d37f4926a0604863927a36174235ac7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"right",
            "location":{
              "x":150,
              "y":206},
            "size":{
              "width":120,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e0f1ced3228497e8fcbe771775a3c3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"right",
                "location":{
                  "x":150,
                  "y":206},
                "size":{
                  "width":120,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f77f4c96487e4ceaa48a2e4118a0f85e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":128},
            "size":{
              "width":800,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本资料/u33_line.png"}},
{
          "id":"645595503d8141bcb18b41f3f2a931f4",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":350,
              "y":160},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79bbada35c5e4c68a7364867c28ce5c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":350,
                  "y":160},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"4e817b0cfe4d48dd8af3c98d8a24261a",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":470,
              "y":160},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4bbc1843cf94aeaa781a257404b8157",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":470,
                  "y":160},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"16170be10f3042f49ca43aa0b6d55996",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":350,
              "y":209},
            "size":{
              "width":300,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ccf3af64f2da4bacb06c0378c2379724",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"right",
            "location":{
              "x":150,
              "y":265},
            "size":{
              "width":120,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34b9c4e841a644d58fe54ba258bae3ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"right",
                "location":{
                  "x":150,
                  "y":265},
                "size":{
                  "width":120,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba1e3f931d404aeca6abdc2017714cc9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"right",
            "location":{
              "x":150,
              "y":338},
            "size":{
              "width":120,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26228bb0a8a34a778695e4b5cea91629",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"right",
                "location":{
                  "x":150,
                  "y":338},
                "size":{
                  "width":120,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f2b855b2b0d4a6dae90a22ba3c6c782",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"right",
            "location":{
              "x":150,
              "y":431},
            "size":{
              "width":117,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4161ed141254d8d95a370c015eaf1f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"right",
                "location":{
                  "x":150,
                  "y":431},
                "size":{
                  "width":117,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84d15a118d1b4b4daca740fb31e62056",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":350,
              "y":263},
            "size":{
              "width":300,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"de58796dd4354537b586fbeab26444c5",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":350,
              "y":310},
            "size":{
              "width":300,
              "height":80}},
          "adaptiveStyles":{
}},
{
          "id":"fd614c11667345d29389b14c43575914",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":350,
              "y":410},
            "size":{
              "width":300,
              "height":80}},
          "adaptiveStyles":{
}},
{
          "id":"029b9f331e1e4ced9e4bd0d66b0ae7be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"right",
            "location":{
              "x":197,
              "y":534},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73b3bb6bcf8645bf946c4884254ce6e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"right",
                "location":{
                  "x":197,
                  "y":534},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dff3568c08b8441ba9c1d65a261f205d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "size":{
              "width":1000,
              "height":98}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3eaf2091b6c413a954791e0f96fffba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "size":{
                  "width":1000,
                  "height":98}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/其它/u24.png"}},
{
          "id":"480135abe56b444bb73455509dfa93cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":290,
              "y":160},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f482de444bb34b81b764eabe4b03d643",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":290,
                  "y":160},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86e7853e0bf94d62bf438113e5174a17",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":290,
              "y":215},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9cb95439bae46c8b8bbf5dcc7061687",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":290,
                  "y":215},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95de54cb8b4040e0b7ac0ebb80eab454",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":290,
              "y":266},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad9655f255b847e8939b515310745b1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":290,
                  "y":266},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8cd2ce4c4fb24cac95f21a33b7373096",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":290,
              "y":338},
            "size":{
              "width":15,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0939382de8ed4e82857e1ed11ade341d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":290,
                  "y":338},
                "size":{
                  "width":15,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"577fac0238e84ea599035799417db9e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":290,
              "y":431},
            "size":{
              "width":15,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"576c4bde0bb441c59c7c5b576058830f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":290,
                  "y":431},
                "size":{
                  "width":15,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"024707695a944709a34635ada05e486e",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":350,
              "y":534},
            "size":{
              "width":480,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ed48da49c2a40c3ae0755cf99110a14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":350,
                  "y":534},
                "size":{
                  "width":480,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"2899f3c6cb57481fa42620ba6347ce32",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":290,
              "y":534},
            "size":{
              "width":15,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbbbeb39818f43258dcfb59921b4c806",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":290,
                  "y":534},
                "size":{
                  "width":15,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "ce6386ad57484fa2812bca34fe8a84de":{
      "scriptId":"u0"},
    "bcd9643eb2f149628ab8c6667f71cc48":{
      "scriptId":"u1"},
    "4c21cc933d4b49b8bc794d03036cde81":{
      "scriptId":"u2"},
    "c941ecc5fe064f27863f630449f18796":{
      "scriptId":"u3"},
    "96ec17f3a98946e687772b5828ff288f":{
      "scriptId":"u4"},
    "d37f4926a0604863927a36174235ac7e":{
      "scriptId":"u5"},
    "4e0f1ced3228497e8fcbe771775a3c3e":{
      "scriptId":"u6"},
    "f77f4c96487e4ceaa48a2e4118a0f85e":{
      "scriptId":"u7"},
    "645595503d8141bcb18b41f3f2a931f4":{
      "scriptId":"u8"},
    "79bbada35c5e4c68a7364867c28ce5c0":{
      "scriptId":"u9"},
    "4e817b0cfe4d48dd8af3c98d8a24261a":{
      "scriptId":"u10"},
    "c4bbc1843cf94aeaa781a257404b8157":{
      "scriptId":"u11"},
    "16170be10f3042f49ca43aa0b6d55996":{
      "scriptId":"u12"},
    "ccf3af64f2da4bacb06c0378c2379724":{
      "scriptId":"u13"},
    "34b9c4e841a644d58fe54ba258bae3ff":{
      "scriptId":"u14"},
    "ba1e3f931d404aeca6abdc2017714cc9":{
      "scriptId":"u15"},
    "26228bb0a8a34a778695e4b5cea91629":{
      "scriptId":"u16"},
    "6f2b855b2b0d4a6dae90a22ba3c6c782":{
      "scriptId":"u17"},
    "e4161ed141254d8d95a370c015eaf1f7":{
      "scriptId":"u18"},
    "84d15a118d1b4b4daca740fb31e62056":{
      "scriptId":"u19"},
    "de58796dd4354537b586fbeab26444c5":{
      "scriptId":"u20"},
    "fd614c11667345d29389b14c43575914":{
      "scriptId":"u21"},
    "029b9f331e1e4ced9e4bd0d66b0ae7be":{
      "scriptId":"u22"},
    "73b3bb6bcf8645bf946c4884254ce6e3":{
      "scriptId":"u23"},
    "dff3568c08b8441ba9c1d65a261f205d":{
      "scriptId":"u24"},
    "c3eaf2091b6c413a954791e0f96fffba":{
      "scriptId":"u25"},
    "480135abe56b444bb73455509dfa93cc":{
      "scriptId":"u26"},
    "f482de444bb34b81b764eabe4b03d643":{
      "scriptId":"u27"},
    "86e7853e0bf94d62bf438113e5174a17":{
      "scriptId":"u28"},
    "f9cb95439bae46c8b8bbf5dcc7061687":{
      "scriptId":"u29"},
    "95de54cb8b4040e0b7ac0ebb80eab454":{
      "scriptId":"u30"},
    "ad9655f255b847e8939b515310745b1e":{
      "scriptId":"u31"},
    "8cd2ce4c4fb24cac95f21a33b7373096":{
      "scriptId":"u32"},
    "0939382de8ed4e82857e1ed11ade341d":{
      "scriptId":"u33"},
    "577fac0238e84ea599035799417db9e6":{
      "scriptId":"u34"},
    "576c4bde0bb441c59c7c5b576058830f":{
      "scriptId":"u35"},
    "024707695a944709a34635ada05e486e":{
      "scriptId":"u36"},
    "3ed48da49c2a40c3ae0755cf99110a14":{
      "scriptId":"u37"},
    "2899f3c6cb57481fa42620ba6347ce32":{
      "scriptId":"u38"},
    "dbbbeb39818f43258dcfb59921b4c806":{
      "scriptId":"u39"}}});