$axure.loadCurrentPage({
  "url":"新增招聘信息.html",
  "generationDate":new Date(1432187597227.73),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9056c5c4ed1a4e9cbf2e0d4f269b449c",
    "type":"Axure:Page",
    "name":"新增招聘信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bdc9b95aeda5467f96e8b02dfd3a4da6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":130,
              "y":100},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1774c04748941b690f57e035f2217b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":130,
                  "y":100},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"353e57a84abc498baa8db0e8cf2d90e8",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":200,
              "y":100},
            "size":{
              "width":150,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"78700986f8fa406bb3eecda66cd82feb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":451,
              "y":100},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75d55aba0af5463e992efb2ee74ffb65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":451,
                  "y":100},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19ced882b9734146bd2a28555661987d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":519,
              "y":95},
            "size":{
              "width":150,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7b8c5c9926b34296b0da3e6b3fd39b3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":130,
              "y":150},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f86362c90ff343748e45642fcadc0584",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":130,
                  "y":150},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"810a623a0973499c9c277bd3227b33ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":451,
              "y":150},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b770bafdf75466992f79973c3005aa6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":451,
                  "y":150},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00069487ac8445729d786f4dd40139e2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":519,
              "y":150},
            "size":{
              "width":150,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"90f9e2822dae41538dc095b9d03b3fa3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":130,
              "y":206},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc08400bf4ae44c58b6228e4c9fe6fce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":130,
                  "y":206},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8513dd6447aa422d879a544797d3493b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":200,
              "y":206},
            "size":{
              "width":150,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a19bef21f86b4b4b84b200a73b502318",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":448,
              "y":206},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f094c906b674ebea305c34f73b9a2dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":448,
                  "y":206},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5126d829a394f14a0fe6b973c554918",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":519,
              "y":206},
            "size":{
              "width":150,
              "height":25}},
          "adaptiveStyles":{
},
          "annotation":{
            "描述":"日期控件"}},
{
          "id":"123e88298e5e424bb631ce106c14b09e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":130,
              "y":264},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"950161d4f0874e838b7b84d6714b7cb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":130,
                  "y":264},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46ef9185419c4f118c96039ff65d2a0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":127,
              "y":324},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"faf6065bc6df465aacd0c00d2ceda8fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":127,
                  "y":324},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"324153e4f0964f9c9f82f085d7b46768",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":199,
              "y":324},
            "size":{
              "width":316,
              "height":100}},
          "adaptiveStyles":{
}},
{
          "id":"0404914334e14397a1737eb928f9e8e3",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":367.5,
              "y":261},
            "size":{
              "width":81,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 硕士基础模板 in New Window/Tab",
                      "target":{
                        "targetType":"page",
                        "url":"硕士基础模板.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true},
{
          "id":"8f71507606a5458ba24adaa9916fc256",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":196,
              "y":483},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 新增招聘信息 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"新增招聘信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"bbc55b22c3c04e4ab071c0a48b22b112",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":330,
              "y":483},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 招聘信息管理 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"招聘信息管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"3aad2aacc50f4a2d93105cca94f8b8e5",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":465,
              "y":483},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 招聘信息管理 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"招聘信息管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"aae119b1c74949179a88465c891e212c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"25px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":356,
              "y":100},
            "size":{
              "width":16,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7fe74c624c04ec6b57de455d443d691",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"25px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":356,
                  "y":100},
                "size":{
                  "width":16,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a8c41f1adb14ee395908692a4ee60a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"25px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":673,
              "y":96},
            "size":{
              "width":24,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"352b2cf73dfd43adb28150a672a07d8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"25px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":673,
                  "y":96},
                "size":{
                  "width":24,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"683caf88657a461ba03f859e651f809f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"25px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":522,
              "y":325},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"677f8300a6e84cb996fd2f077bdd66f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"25px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":522,
                  "y":325},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b6217b78e3f4073ade32463865d0df6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"25px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":674,
              "y":206},
            "size":{
              "width":24,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77d63efcdf25410cb36609150e87d9ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"25px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":674,
                  "y":206},
                "size":{
                  "width":24,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"339d381d932f4c9d87289f3e7db0fb94",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":357,
              "y":207},
            "size":{
              "width":24,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f76b28bc38d4424793ab0274abebee93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":357,
                  "y":207},
                "size":{
                  "width":24,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38a670b9ed9e4088814eaf956b6308f4",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":200,
              "y":264},
            "size":{
              "width":150,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"9aa0149b6f2349428561af184de47534",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"030ad16089984aab8ee4c9e9409d1f39"},
{
          "id":"1ae9cb75b6fc40849f4102bbeaffeea0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":378,
              "y":209},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b8e228ed1e149cdbbe5ca76e70ac98b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":378,
                  "y":209},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"098cb66be18a48418e0d70fac0ef88cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":123,
              "y":64},
            "size":{
              "width":171,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"651ba23a740a4f499876fcde4b9d1a9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":123,
                  "y":64},
                "size":{
                  "width":171,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"700fa88c56604e1eb9607e12da9806ba",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":196,
              "y":149},
            "size":{
              "width":154,
              "height":26}},
          "adaptiveStyles":{
}}]}},
  "masters":{
    "030ad16089984aab8ee4c9e9409d1f39":{
      "packageId":"030ad16089984aab8ee4c9e9409d1f39",
      "type":"Axure:Master",
      "name":"人才招聘管理系统后台",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9232e32197a446c6ab3ac4fe47afb413",
            "label":"",
            "type":"menuObject",
            "styleType":"menuObject",
            "visible":true,
            "style":{
              "location":{
                "x":3,
                "y":86},
              "size":{
                "width":94,
                "height":206}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"988f442a183f4ee88509cc6f7639e83e",
                "label":"",
                "type":"table",
                "styleType":"table",
                "visible":true,
                "style":{
                  "fontName":"'应用字体 Regular', '应用字体'",
                  "location":{
                    "x":1,
                    "y":1},
                  "size":{
                    "width":92,
                    "height":204}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"fed27e3024fc4271bf03fd915426fc55",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontName":"'应用字体 Regular', '应用字体'",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "size":{
                        "width":92,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"28425b724562437284c1b3413ebfbc1b",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'应用字体 Regular', '应用字体'",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":92,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 招聘信息管理 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"招聘信息管理.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/招聘信息管理/u148.png"}},
{
                    "id":"7cc6daf02f5846e488a2e43229e8cbdb",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontName":"'应用字体 Regular', '应用字体'",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":40},
                      "size":{
                        "width":92,
                        "height":41}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"34f6be30c9ec4109a5627e1ea10be8a3",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'应用字体 Regular', '应用字体'",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":40},
                          "size":{
                            "width":92,
                            "height":41}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 简历模板管理 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"简历模板管理.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/招聘信息管理/u150.png"}},
{
                    "id":"6beabc4a41534830ae47bf6e5f5ac0cf",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontName":"'应用字体 Regular', '应用字体'",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":81},
                      "size":{
                        "width":92,
                        "height":41}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8dc40013972144dd844af24ead8557cb",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'应用字体 Regular', '应用字体'",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":81},
                          "size":{
                            "width":92,
                            "height":41}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 求职管理 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"求职管理.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/招聘信息管理/u150.png"}},
{
                    "id":"60510bcddbd34329b465172645d875fe",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontName":"'应用字体 Regular', '应用字体'",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":122},
                      "size":{
                        "width":92,
                        "height":41}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"89165b05ac1840c587b8073c47727ae5",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'应用字体 Regular', '应用字体'",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":122},
                          "size":{
                            "width":92,
                            "height":41}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 通知公告 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"通知公告.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/招聘信息管理/u150.png"}},
{
                    "id":"100a2cff887c468f84258eb7cf40101f",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontName":"'应用字体 Regular', '应用字体'",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":163},
                      "size":{
                        "width":92,
                        "height":41}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"fd9868620ceb4fba841cce604260b30c",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'应用字体 Regular', '应用字体'",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":163},
                          "size":{
                            "width":92,
                            "height":41}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 用户管理 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"用户管理.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/招聘信息管理/u156.png"}}]},
{
                "id":"232cc5fe273e448baa605b9679ab1ea8",
                "label":"",
                "type":"menuObject",
                "styleType":"menuObject",
                "visible":true,
                "style":{
                  "location":{
                    "x":93,
                    "y":1},
                  "size":{
                    "width":102,
                    "height":68},
                  "limbo":false},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"99399b02f1d643098b720d4f14369786",
                    "label":"",
                    "type":"table",
                    "styleType":"table",
                    "visible":true,
                    "style":{
                      "fontName":"'应用字体 Regular', '应用字体'",
                      "location":{
                        "x":1,
                        "y":1},
                      "size":{
                        "width":100,
                        "height":66}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8323f9cffe7e4cd08a4ec28dcd3fa16e",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontName":"'应用字体 Regular', '应用字体'",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":100,
                            "height":33},
                          "limbo":false},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"7dfe4ab4347a4ec8b511ac98b57dad5d",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'应用字体 Regular', '应用字体'",
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "size":{
                                "width":100,
                                "height":33},
                              "limbo":false},
                            "adaptiveStyles":{
}}],
                        "interactionMap":{
                          "onClick":{
                            "description":"OnClick",
                            "cases":[{
                                "description":"用例 1",
                                "isNewIfGroup":false,
                                "actions":[{
                                    "action":"linkWindow",
                                    "description":"Open 新增招聘信息 in Current Window",
                                    "target":{
                                      "targetType":"page",
                                      "url":"新增招聘信息.html",
                                      "includeVariables":true},
                                    "linkType":"current"}]}]}},
                        "tabbable":true,
                        "images":{
                          "normal~":"images/招聘信息管理/u160.png"}},
{
                        "id":"c45240286e9d4788aa19b732de47b8ec",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontName":"'应用字体 Regular', '应用字体'",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":33},
                          "size":{
                            "width":100,
                            "height":33},
                          "limbo":false},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"31abfc6f378c42999e2ed0eb20851788",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'应用字体 Regular', '应用字体'",
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "location":{
                                "x":0,
                                "y":33},
                              "size":{
                                "width":100,
                                "height":33},
                              "limbo":false},
                            "adaptiveStyles":{
}}],
                        "interactionMap":{
                          "onClick":{
                            "description":"OnClick",
                            "cases":[{
                                "description":"用例 1",
                                "isNewIfGroup":false,
                                "actions":[{
                                    "action":"linkWindow",
                                    "description":"Open 招聘信息详情 in Current Window",
                                    "target":{
                                      "targetType":"page",
                                      "url":"招聘信息详情.html",
                                      "includeVariables":true},
                                    "linkType":"current"}]}]}},
                        "tabbable":true,
                        "images":{
                          "normal~":"images/招聘信息管理/u162.png"}}]}],
                "parentCellId":"fed27e3024fc4271bf03fd915426fc55"},
{
                "id":"657a840bbdc540a98b516330bc563ca0",
                "label":"",
                "type":"menuObject",
                "styleType":"menuObject",
                "visible":true,
                "style":{
                  "location":{
                    "x":93,
                    "y":82},
                  "size":{
                    "width":102,
                    "height":30},
                  "limbo":false},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"9520925f43104ff19c135876b0a876ee",
                    "label":"",
                    "type":"table",
                    "styleType":"table",
                    "visible":true,
                    "style":{
                      "fontName":"'应用字体 Regular', '应用字体'",
                      "location":{
                        "x":1,
                        "y":1},
                      "size":{
                        "width":100,
                        "height":28}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"dd6a6aa65d7c49c08eaf2897402c1774",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontName":"'应用字体 Regular', '应用字体'",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":100,
                            "height":28},
                          "limbo":false},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"4ca2153f19564050b1b0b79d048af6be",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'应用字体 Regular', '应用字体'",
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "size":{
                                "width":100,
                                "height":28},
                              "limbo":false},
                            "adaptiveStyles":{
}}],
                        "interactionMap":{
                          "onClick":{
                            "description":"OnClick",
                            "cases":[{
                                "description":"用例 1",
                                "isNewIfGroup":false,
                                "actions":[{
                                    "action":"linkWindow",
                                    "description":"Open 求职简历 in Current Window",
                                    "target":{
                                      "targetType":"page",
                                      "url":"求职简历.html",
                                      "includeVariables":true},
                                    "linkType":"current"}]}]}},
                        "tabbable":true,
                        "images":{
                          "normal~":"images/招聘信息管理/u166.png"}}]}],
                "parentCellId":"6beabc4a41534830ae47bf6e5f5ac0cf"}]},
{
            "id":"77952284bd3b4c3697e2e700fa8e9f69",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'应用字体 Regular', '应用字体'",
              "location":{
                "x":10,
                "y":10},
              "size":{
                "width":240,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8605d38b30644110a6b7d7589b917ffe",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'应用字体 Regular', '应用字体'",
                  "location":{
                    "x":10,
                    "y":10},
                  "size":{
                    "width":240,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/人才招聘管理系统后台/u7.png"}},
{
            "id":"52b40107394d4a95973feb78feef7962",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'应用字体 Regular', '应用字体'",
              "location":{
                "x":266,
                "y":12},
              "size":{
                "width":366,
                "height":38}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6d6781c266174d28a530084ef993c2e5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'应用字体 Regular', '应用字体'",
                  "location":{
                    "x":266,
                    "y":12},
                  "size":{
                    "width":366,
                    "height":38}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"de5b16e20ea14d4ca5b691a7d6e768a7",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'应用字体 Regular', '应用字体'",
              "location":{
                "x":970,
                "y":63},
              "size":{
                "width":88,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4b9c250708264d5caf1ddcf8c5b4a78d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'应用字体 Regular', '应用字体'",
                  "location":{
                    "x":970,
                    "y":63},
                  "size":{
                    "width":88,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4e54640567e942f78265fdbc723ce477",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":114,
                "y":80},
              "size":{
                "width":1000,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/人才招聘管理系统后台/u11_line.png"}}]}}},
  "objectPaths":{
    "bdc9b95aeda5467f96e8b02dfd3a4da6":{
      "scriptId":"u0"},
    "e1774c04748941b690f57e035f2217b3":{
      "scriptId":"u1"},
    "353e57a84abc498baa8db0e8cf2d90e8":{
      "scriptId":"u2"},
    "78700986f8fa406bb3eecda66cd82feb":{
      "scriptId":"u3"},
    "75d55aba0af5463e992efb2ee74ffb65":{
      "scriptId":"u4"},
    "19ced882b9734146bd2a28555661987d":{
      "scriptId":"u5"},
    "7b8c5c9926b34296b0da3e6b3fd39b3b":{
      "scriptId":"u6"},
    "f86362c90ff343748e45642fcadc0584":{
      "scriptId":"u7"},
    "810a623a0973499c9c277bd3227b33ab":{
      "scriptId":"u8"},
    "5b770bafdf75466992f79973c3005aa6":{
      "scriptId":"u9"},
    "00069487ac8445729d786f4dd40139e2":{
      "scriptId":"u10"},
    "90f9e2822dae41538dc095b9d03b3fa3":{
      "scriptId":"u11"},
    "bc08400bf4ae44c58b6228e4c9fe6fce":{
      "scriptId":"u12"},
    "8513dd6447aa422d879a544797d3493b":{
      "scriptId":"u13"},
    "a19bef21f86b4b4b84b200a73b502318":{
      "scriptId":"u14"},
    "9f094c906b674ebea305c34f73b9a2dc":{
      "scriptId":"u15"},
    "f5126d829a394f14a0fe6b973c554918":{
      "scriptId":"u16"},
    "123e88298e5e424bb631ce106c14b09e":{
      "scriptId":"u17"},
    "950161d4f0874e838b7b84d6714b7cb3":{
      "scriptId":"u18"},
    "46ef9185419c4f118c96039ff65d2a0b":{
      "scriptId":"u19"},
    "faf6065bc6df465aacd0c00d2ceda8fa":{
      "scriptId":"u20"},
    "324153e4f0964f9c9f82f085d7b46768":{
      "scriptId":"u21"},
    "0404914334e14397a1737eb928f9e8e3":{
      "scriptId":"u22"},
    "8f71507606a5458ba24adaa9916fc256":{
      "scriptId":"u23"},
    "bbc55b22c3c04e4ab071c0a48b22b112":{
      "scriptId":"u24"},
    "3aad2aacc50f4a2d93105cca94f8b8e5":{
      "scriptId":"u25"},
    "aae119b1c74949179a88465c891e212c":{
      "scriptId":"u26"},
    "e7fe74c624c04ec6b57de455d443d691":{
      "scriptId":"u27"},
    "2a8c41f1adb14ee395908692a4ee60a9":{
      "scriptId":"u28"},
    "352b2cf73dfd43adb28150a672a07d8d":{
      "scriptId":"u29"},
    "683caf88657a461ba03f859e651f809f":{
      "scriptId":"u30"},
    "677f8300a6e84cb996fd2f077bdd66f9":{
      "scriptId":"u31"},
    "0b6217b78e3f4073ade32463865d0df6":{
      "scriptId":"u32"},
    "77d63efcdf25410cb36609150e87d9ad":{
      "scriptId":"u33"},
    "339d381d932f4c9d87289f3e7db0fb94":{
      "scriptId":"u34"},
    "f76b28bc38d4424793ab0274abebee93":{
      "scriptId":"u35"},
    "38a670b9ed9e4088814eaf956b6308f4":{
      "scriptId":"u36"},
    "9aa0149b6f2349428561af184de47534":{
      "scriptId":"u37",
      "9232e32197a446c6ab3ac4fe47afb413":{
        "scriptId":"u38"},
      "988f442a183f4ee88509cc6f7639e83e":{
        "scriptId":"u39"},
      "fed27e3024fc4271bf03fd915426fc55":{
        "scriptId":"u40"},
      "28425b724562437284c1b3413ebfbc1b":{
        "scriptId":"u41"},
      "7cc6daf02f5846e488a2e43229e8cbdb":{
        "scriptId":"u42"},
      "34f6be30c9ec4109a5627e1ea10be8a3":{
        "scriptId":"u43"},
      "6beabc4a41534830ae47bf6e5f5ac0cf":{
        "scriptId":"u44"},
      "8dc40013972144dd844af24ead8557cb":{
        "scriptId":"u45"},
      "60510bcddbd34329b465172645d875fe":{
        "scriptId":"u46"},
      "89165b05ac1840c587b8073c47727ae5":{
        "scriptId":"u47"},
      "100a2cff887c468f84258eb7cf40101f":{
        "scriptId":"u48"},
      "fd9868620ceb4fba841cce604260b30c":{
        "scriptId":"u49"},
      "232cc5fe273e448baa605b9679ab1ea8":{
        "scriptId":"u50"},
      "99399b02f1d643098b720d4f14369786":{
        "scriptId":"u51"},
      "8323f9cffe7e4cd08a4ec28dcd3fa16e":{
        "scriptId":"u52"},
      "7dfe4ab4347a4ec8b511ac98b57dad5d":{
        "scriptId":"u53"},
      "c45240286e9d4788aa19b732de47b8ec":{
        "scriptId":"u54"},
      "31abfc6f378c42999e2ed0eb20851788":{
        "scriptId":"u55"},
      "657a840bbdc540a98b516330bc563ca0":{
        "scriptId":"u56"},
      "9520925f43104ff19c135876b0a876ee":{
        "scriptId":"u57"},
      "dd6a6aa65d7c49c08eaf2897402c1774":{
        "scriptId":"u58"},
      "4ca2153f19564050b1b0b79d048af6be":{
        "scriptId":"u59"},
      "77952284bd3b4c3697e2e700fa8e9f69":{
        "scriptId":"u60"},
      "8605d38b30644110a6b7d7589b917ffe":{
        "scriptId":"u61"},
      "52b40107394d4a95973feb78feef7962":{
        "scriptId":"u62"},
      "6d6781c266174d28a530084ef993c2e5":{
        "scriptId":"u63"},
      "de5b16e20ea14d4ca5b691a7d6e768a7":{
        "scriptId":"u64"},
      "4b9c250708264d5caf1ddcf8c5b4a78d":{
        "scriptId":"u65"},
      "4e54640567e942f78265fdbc723ce477":{
        "scriptId":"u66"}},
    "1ae9cb75b6fc40849f4102bbeaffeea0":{
      "scriptId":"u67"},
    "3b8e228ed1e149cdbbe5ca76e70ac98b":{
      "scriptId":"u68"},
    "098cb66be18a48418e0d70fac0ef88cb":{
      "scriptId":"u69"},
    "651ba23a740a4f499876fcde4b9d1a9a":{
      "scriptId":"u70"},
    "700fa88c56604e1eb9607e12da9806ba":{
      "scriptId":"u71"}}});