$axure.loadCurrentPage({
  "url":"正骨医院人才招聘首页.html",
  "generationDate":new Date(1432187595932.73),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"124462f9fc954c81ab4beccffb7c9333",
    "type":"Axure:Page",
    "name":"正骨医院人才招聘首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d2ec558e00ae412680d85ec680aac1f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"left",
            "location":{
              "x":50,
              "y":210},
            "size":{
              "width":260,
              "height":610}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8843e3493e74eca89dec4e26cf07792",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"left",
                "location":{
                  "x":50,
                  "y":210},
                "size":{
                  "width":260,
                  "height":610}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 通知公告详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"通知公告详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/正骨医院人才招聘首页/u0.png"}},
{
          "id":"76e6a9c129be4e4ab5662dd0c9a9069b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":330,
              "y":106},
            "size":{
              "width":820,
              "height":715}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa26d9a72d95465595bb3d31088d59b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":330,
                  "y":106},
                "size":{
                  "width":820,
                  "height":715}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/正骨医院人才招聘首页/u2.png"}},
{
          "id":"b0c22c11823141be8e5615ad75f568ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":342,
              "y":111},
            "size":{
              "width":80,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83e5c68aeaa44bef91ef47cf5e892eb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":342,
                  "y":111},
                "size":{
                  "width":80,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5df29485cb8470e9c33bf080797c84f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":358,
              "y":144},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcb93473d09041878e6711edbb3b62e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":358,
                  "y":144},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5b365ed55424e2bb96d0de01745fc86",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":599,
              "y":144},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09790cf4f8984c91916abca5e4cbec38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":599,
                  "y":144},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b701a0efc21437e99161c3041938375",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":416,
              "y":144},
            "size":{
              "width":124,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1066450ff12b4cbea947c96db5bb56bb",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":634,
              "y":144},
            "size":{
              "width":129,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"082613d12a5b4cf38a7351ffa624f257",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":1052,
              "y":144},
            "size":{
              "width":58,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"66a14c75d6ca455081788f9dc0cabcdc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"left",
            "location":{
              "x":355,
              "y":178},
            "size":{
              "width":785,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6eee0a314b2a4831828c94ee6f6e1b05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"left",
                "location":{
                  "x":355,
                  "y":178},
                "size":{
                  "width":785,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/正骨医院人才招聘首页/u13.png"}},
{
          "id":"f841255317e844f989a4026288490acb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":813,
              "y":144},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80b737c65dcd4e8e95790dd5dd5d3e82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":813,
                  "y":144},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50b2b17bc1b1467090c1b1dc49f801a4",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":871,
              "y":144},
            "size":{
              "width":119,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8700113b072c4ca4a775a705e23ab0bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":50,
              "y":106},
            "size":{
              "width":260,
              "height":74}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b45466b5c9c48979df59609955f0e47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":50,
                  "y":106},
                "size":{
                  "width":260,
                  "height":74}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/正骨医院人才招聘首页/u18.png"}},
{
          "id":"8f2d60e1d53e417a9671b89c4fae38a9",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":112},
            "size":{
              "width":234,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffa0f5beff51465eb0a1c7ae1eed4281",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "size":{
                  "width":234,
                  "height":63}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9e55c54b364d4b49a7d8d680b2d3c765",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":234,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fdce3d5e8282485995220f26db4e9501",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'应用字体 Regular', '应用字体'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":234,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/正骨医院人才招聘首页/u22.png"}},
{
                  "id":"b61f7cf33b9d40aebf78312c25ce3b6c",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":234,
                      "height":33}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c88f92f834e046ab8393f38a5a15ce4c",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'应用字体 Regular', '应用字体'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":234,
                          "height":33}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"c763a286a58b4a3b8af2c2233658653a",
                          "label":"",
                          "type":"hyperlink",
                          "styleType":"hyperlink",
                          "visible":true,
                          "style":{
                            "fontName":"'应用字体 Regular', '应用字体'"},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"Open 求职反馈 in Current Window",
                                      "target":{
                                        "targetType":"page",
                                        "url":"求职反馈.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true}]}],
                  "images":{
                    "normal~":"images/正骨医院人才招聘首页/u24.png"}}]}]},
{
          "id":"56c695c63b2d406e8f5dbe6db860273a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "size":{
              "width":1150,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10fb8253fd4142d68c6f64b0f656b5aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "size":{
                  "width":1150,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/正骨医院人才招聘首页/u27.png"}},
{
          "id":"4ab55349b71e4387961188051cb64ccf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":140,
              "y":219},
            "size":{
              "width":80,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1d6ca27114b4714acd805f8aef3bf79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":140,
                  "y":219},
                "size":{
                  "width":80,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2852909b3abc48e886c69a423e3005ef",
          "label":"展开框",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"left",
            "location":{
              "x":355.5,
              "y":222},
            "size":{
              "width":785,
              "height":142}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56ad51cbdd3f4c55af587275e1da6030",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"left",
                "location":{
                  "x":355.5,
                  "y":222},
                "size":{
                  "width":785,
                  "height":142}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/正骨医院人才招聘首页/展开框_u31.png"}},
{
          "id":"8210d0d3e17547c5b65b0660771f7550",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"left",
            "location":{
              "x":355,
              "y":374},
            "size":{
              "width":785,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3792e3cc25b849a682eb9a00b2139c0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"left",
                "location":{
                  "x":355,
                  "y":374},
                "size":{
                  "width":785,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/正骨医院人才招聘首页/u33.png"}},
{
          "id":"18e2f86327c5455fa4788fb2af613fa7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"left",
            "location":{
              "x":355,
              "y":416},
            "size":{
              "width":785,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"635b7371dd2b4c229b05e52c42c4bd59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"left",
                "location":{
                  "x":355,
                  "y":416},
                "size":{
                  "width":785,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/正骨医院人才招聘首页/u33.png"}},
{
          "id":"eca087e71cea44179ea4c18cc8fde5e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":355,
              "y":790},
            "size":{
              "width":202,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94a1317b47714ee58e28054041a5a2ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":355,
                  "y":790},
                "size":{
                  "width":202,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d77e1d64b8a84ee1b470c54e9559c254",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"left",
            "location":{
              "x":355,
              "y":458},
            "size":{
              "width":785,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67e65e4082014dd88242122f348d5b11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"left",
                "location":{
                  "x":355,
                  "y":458},
                "size":{
                  "width":785,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/正骨医院人才招聘首页/u13.png"}},
{
          "id":"916490c7de9b4b19a16f1d3170e33b3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"left",
            "location":{
              "x":355,
              "y":500},
            "size":{
              "width":785,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b99faef57c04e9bb79512332776dc25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"left",
                "location":{
                  "x":355,
                  "y":500},
                "size":{
                  "width":785,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/正骨医院人才招聘首页/u13.png"}},
{
          "id":"7d960dd3351749f1bd29c2e9a86df5a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"left",
            "location":{
              "x":355,
              "y":538},
            "size":{
              "width":785,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0e649ed9c1b49a79d0ec9a7c5e0cdaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"left",
                "location":{
                  "x":355,
                  "y":538},
                "size":{
                  "width":785,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/正骨医院人才招聘首页/u13.png"}},
{
          "id":"f828a37f4d944866a6f51b10828d716f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":1052,
              "y":182},
            "size":{
              "width":58,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a84bb958625d4d6bac676c28aa5bcba1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"left",
            "location":{
              "x":355,
              "y":618},
            "size":{
              "width":785,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e2e1b930a454ee1b95958082d0933fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"left",
                "location":{
                  "x":355,
                  "y":618},
                "size":{
                  "width":785,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/正骨医院人才招聘首页/u13.png"}},
{
          "id":"944438d560dc4cd4b5a427c4cb984404",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"left",
            "location":{
              "x":355,
              "y":578},
            "size":{
              "width":785,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f5f7b471e7c465ba3a9d0786aab5f67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"left",
                "location":{
                  "x":355,
                  "y":578},
                "size":{
                  "width":785,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/正骨医院人才招聘首页/u33.png"}},
{
          "id":"7ab710477ee042928c384b9e10d5dd40",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"left",
            "location":{
              "x":355,
              "y":658},
            "size":{
              "width":785,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"850c45dc0ae5488e9f7d6920552e3f66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"left",
                "location":{
                  "x":355,
                  "y":658},
                "size":{
                  "width":785,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/正骨医院人才招聘首页/u13.png"}},
{
          "id":"d181334268404d509cd959e1d0c8122b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"left",
            "location":{
              "x":355,
              "y":700},
            "size":{
              "width":785,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e947af5e49854dd2ba9c3f55867b542a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"left",
                "location":{
                  "x":355,
                  "y":700},
                "size":{
                  "width":785,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/正骨医院人才招聘首页/u13.png"}},
{
          "id":"395e1691f03a4cd2a0d5ab765a5181c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"left",
            "location":{
              "x":355,
              "y":738},
            "size":{
              "width":785,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"332308f0516c4138a39f90718d314f59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"left",
                "location":{
                  "x":355,
                  "y":738},
                "size":{
                  "width":785,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/正骨医院人才招聘首页/u13.png"}},
{
          "id":"a7952422c0b64711aff37a76172265dd",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":1052,
              "y":227},
            "size":{
              "width":58,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5473c39069604a009084be1f242fb3bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":453,
              "y":230},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45c42567dedd47edba17fbf0470f7e6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":453,
                  "y":230},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84b493fe94434014bf7d87c77b91cb98",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":708,
              "y":250},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b759818ba2b2419eb87c2309fe86ab44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":708,
                  "y":250},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ae8cf2c315b4ee4b73aad2f3ceb191f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":453,
              "y":250},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dfd9ef102da46a3b7487045bc8776fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":453,
                  "y":250},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1df6e464c3ce4db3b27fe5ebc5bf4ae3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":708,
              "y":230},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c78e7de0f4b3462ca472355f737da292",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":708,
                  "y":230},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da4fe8c083d24b0190e80c861a4517be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":453,
              "y":270},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f3e0b39b51a40fd8add74a102b8a90c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":453,
                  "y":270},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2458dbf76f68414fb1250e9659606151",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":708,
              "y":270},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"beb9e4ca5c734e5f8dce8bd6054f0262",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":708,
                  "y":270},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2073aca9a09c4942b8801871de9af6fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":453,
              "y":290},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16fb8b7301c440fa8e35cdf0fd1a3a21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":453,
                  "y":290},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8131f9ca81534c768c1de91c52dbd6a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":533,
              "y":290},
            "size":{
              "width":360,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96ee55b12ec24105b3c222a3e86f9869",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":533,
                  "y":290},
                "size":{
                  "width":360,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"003856e19b4748b1a3937c68217c2845",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":533,
              "y":230},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58822817135a4b6ca7f19bb497685f9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":533,
                  "y":230},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96f9f55e85094d0386a6637a7b88f6f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":533,
              "y":250},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"731ea436272645c6b22065a02f39d259",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":533,
                  "y":250},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d0fd92a6b2043ab80228f77924c1e37",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":533,
              "y":270},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64df3ca0f7324e2d9ec80075a1f75b2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":533,
                  "y":270},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6a2afa1b36148b8a8d9e308da161b7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":798,
              "y":250},
            "size":{
              "width":80,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"badccc72f4584133adc4c9f471809769",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":798,
                  "y":250},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"acd61680e6ed485eafe57e30ec12a5c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":798,
              "y":230},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86a2caafdb0e4a678d2aac58327aad03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":798,
                  "y":230},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"154215f844754e009b640b7609c07b02",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":800,
              "y":270},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0372e5c767147e690e472aeece4ef8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":800,
                  "y":270},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a37c652413194bba88fee87d56188905",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":640,
              "y":332},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 身份验证 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"身份验证.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"de4ee6f967b4488ba69055c428a5400c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":50,
              "y":832},
            "size":{
              "width":270,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"655eecd1a3d44601ba7baf5fb31e9df6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":832},
                "size":{
                  "width":270,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "d2ec558e00ae412680d85ec680aac1f3":{
      "scriptId":"u0"},
    "e8843e3493e74eca89dec4e26cf07792":{
      "scriptId":"u1"},
    "76e6a9c129be4e4ab5662dd0c9a9069b":{
      "scriptId":"u2"},
    "fa26d9a72d95465595bb3d31088d59b1":{
      "scriptId":"u3"},
    "b0c22c11823141be8e5615ad75f568ec":{
      "scriptId":"u4"},
    "83e5c68aeaa44bef91ef47cf5e892eb1":{
      "scriptId":"u5"},
    "c5df29485cb8470e9c33bf080797c84f":{
      "scriptId":"u6"},
    "dcb93473d09041878e6711edbb3b62e2":{
      "scriptId":"u7"},
    "b5b365ed55424e2bb96d0de01745fc86":{
      "scriptId":"u8"},
    "09790cf4f8984c91916abca5e4cbec38":{
      "scriptId":"u9"},
    "8b701a0efc21437e99161c3041938375":{
      "scriptId":"u10"},
    "1066450ff12b4cbea947c96db5bb56bb":{
      "scriptId":"u11"},
    "082613d12a5b4cf38a7351ffa624f257":{
      "scriptId":"u12"},
    "66a14c75d6ca455081788f9dc0cabcdc":{
      "scriptId":"u13"},
    "6eee0a314b2a4831828c94ee6f6e1b05":{
      "scriptId":"u14"},
    "f841255317e844f989a4026288490acb":{
      "scriptId":"u15"},
    "80b737c65dcd4e8e95790dd5dd5d3e82":{
      "scriptId":"u16"},
    "50b2b17bc1b1467090c1b1dc49f801a4":{
      "scriptId":"u17"},
    "8700113b072c4ca4a775a705e23ab0bb":{
      "scriptId":"u18"},
    "9b45466b5c9c48979df59609955f0e47":{
      "scriptId":"u19"},
    "8f2d60e1d53e417a9671b89c4fae38a9":{
      "scriptId":"u20"},
    "ffa0f5beff51465eb0a1c7ae1eed4281":{
      "scriptId":"u21"},
    "9e55c54b364d4b49a7d8d680b2d3c765":{
      "scriptId":"u22"},
    "fdce3d5e8282485995220f26db4e9501":{
      "scriptId":"u23"},
    "b61f7cf33b9d40aebf78312c25ce3b6c":{
      "scriptId":"u24"},
    "c88f92f834e046ab8393f38a5a15ce4c":{
      "scriptId":"u25"},
    "c763a286a58b4a3b8af2c2233658653a":{
      "scriptId":"u26"},
    "56c695c63b2d406e8f5dbe6db860273a":{
      "scriptId":"u27"},
    "10fb8253fd4142d68c6f64b0f656b5aa":{
      "scriptId":"u28"},
    "4ab55349b71e4387961188051cb64ccf":{
      "scriptId":"u29"},
    "a1d6ca27114b4714acd805f8aef3bf79":{
      "scriptId":"u30"},
    "2852909b3abc48e886c69a423e3005ef":{
      "scriptId":"u31"},
    "56ad51cbdd3f4c55af587275e1da6030":{
      "scriptId":"u32"},
    "8210d0d3e17547c5b65b0660771f7550":{
      "scriptId":"u33"},
    "3792e3cc25b849a682eb9a00b2139c0f":{
      "scriptId":"u34"},
    "18e2f86327c5455fa4788fb2af613fa7":{
      "scriptId":"u35"},
    "635b7371dd2b4c229b05e52c42c4bd59":{
      "scriptId":"u36"},
    "eca087e71cea44179ea4c18cc8fde5e6":{
      "scriptId":"u37"},
    "94a1317b47714ee58e28054041a5a2ef":{
      "scriptId":"u38"},
    "d77e1d64b8a84ee1b470c54e9559c254":{
      "scriptId":"u39"},
    "67e65e4082014dd88242122f348d5b11":{
      "scriptId":"u40"},
    "916490c7de9b4b19a16f1d3170e33b3d":{
      "scriptId":"u41"},
    "5b99faef57c04e9bb79512332776dc25":{
      "scriptId":"u42"},
    "7d960dd3351749f1bd29c2e9a86df5a0":{
      "scriptId":"u43"},
    "e0e649ed9c1b49a79d0ec9a7c5e0cdaf":{
      "scriptId":"u44"},
    "f828a37f4d944866a6f51b10828d716f":{
      "scriptId":"u45"},
    "a84bb958625d4d6bac676c28aa5bcba1":{
      "scriptId":"u46"},
    "9e2e1b930a454ee1b95958082d0933fb":{
      "scriptId":"u47"},
    "944438d560dc4cd4b5a427c4cb984404":{
      "scriptId":"u48"},
    "9f5f7b471e7c465ba3a9d0786aab5f67":{
      "scriptId":"u49"},
    "7ab710477ee042928c384b9e10d5dd40":{
      "scriptId":"u50"},
    "850c45dc0ae5488e9f7d6920552e3f66":{
      "scriptId":"u51"},
    "d181334268404d509cd959e1d0c8122b":{
      "scriptId":"u52"},
    "e947af5e49854dd2ba9c3f55867b542a":{
      "scriptId":"u53"},
    "395e1691f03a4cd2a0d5ab765a5181c8":{
      "scriptId":"u54"},
    "332308f0516c4138a39f90718d314f59":{
      "scriptId":"u55"},
    "a7952422c0b64711aff37a76172265dd":{
      "scriptId":"u56"},
    "5473c39069604a009084be1f242fb3bb":{
      "scriptId":"u57"},
    "45c42567dedd47edba17fbf0470f7e6f":{
      "scriptId":"u58"},
    "84b493fe94434014bf7d87c77b91cb98":{
      "scriptId":"u59"},
    "b759818ba2b2419eb87c2309fe86ab44":{
      "scriptId":"u60"},
    "9ae8cf2c315b4ee4b73aad2f3ceb191f":{
      "scriptId":"u61"},
    "2dfd9ef102da46a3b7487045bc8776fa":{
      "scriptId":"u62"},
    "1df6e464c3ce4db3b27fe5ebc5bf4ae3":{
      "scriptId":"u63"},
    "c78e7de0f4b3462ca472355f737da292":{
      "scriptId":"u64"},
    "da4fe8c083d24b0190e80c861a4517be":{
      "scriptId":"u65"},
    "1f3e0b39b51a40fd8add74a102b8a90c":{
      "scriptId":"u66"},
    "2458dbf76f68414fb1250e9659606151":{
      "scriptId":"u67"},
    "beb9e4ca5c734e5f8dce8bd6054f0262":{
      "scriptId":"u68"},
    "2073aca9a09c4942b8801871de9af6fb":{
      "scriptId":"u69"},
    "16fb8b7301c440fa8e35cdf0fd1a3a21":{
      "scriptId":"u70"},
    "8131f9ca81534c768c1de91c52dbd6a5":{
      "scriptId":"u71"},
    "96ee55b12ec24105b3c222a3e86f9869":{
      "scriptId":"u72"},
    "003856e19b4748b1a3937c68217c2845":{
      "scriptId":"u73"},
    "58822817135a4b6ca7f19bb497685f9a":{
      "scriptId":"u74"},
    "96f9f55e85094d0386a6637a7b88f6f3":{
      "scriptId":"u75"},
    "731ea436272645c6b22065a02f39d259":{
      "scriptId":"u76"},
    "7d0fd92a6b2043ab80228f77924c1e37":{
      "scriptId":"u77"},
    "64df3ca0f7324e2d9ec80075a1f75b2c":{
      "scriptId":"u78"},
    "e6a2afa1b36148b8a8d9e308da161b7f":{
      "scriptId":"u79"},
    "badccc72f4584133adc4c9f471809769":{
      "scriptId":"u80"},
    "acd61680e6ed485eafe57e30ec12a5c8":{
      "scriptId":"u81"},
    "86a2caafdb0e4a678d2aac58327aad03":{
      "scriptId":"u82"},
    "154215f844754e009b640b7609c07b02":{
      "scriptId":"u83"},
    "a0372e5c767147e690e472aeece4ef8a":{
      "scriptId":"u84"},
    "a37c652413194bba88fee87d56188905":{
      "scriptId":"u85"},
    "de4ee6f967b4488ba69055c428a5400c":{
      "scriptId":"u86"},
    "655eecd1a3d44601ba7baf5fb31e9df6":{
      "scriptId":"u87"}}});