$axure.loadCurrentPage({
  "url":"用户管理.html",
  "generationDate":new Date(1432187598975.73),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9e6b43b7b0d340479890a0bbab9f28eb",
    "type":"Axure:Page",
    "name":"用户管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dc7ab9cfaa5a441ab336d88b41197cb9",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":126,
              "y":154},
            "size":{
              "width":576,
              "height":179}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94f10565a6bb451aa05473d705ea7f81",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":46,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6a7d3e92fa7947fc8ec1765b60a4b38e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":46,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u1.png"}},
{
              "id":"b05e61e7350b462d83a3bb2846135aef",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":29},
                "size":{
                  "width":46,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5de3f5bd86f9435496c52d8fc6d1dc03",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":29},
                    "size":{
                      "width":46,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/硕士模板/u1.png"}},
{
              "id":"8956a5877bbd4602b4bac7d7f520420c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":89},
                "size":{
                  "width":46,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b22480a1b7a6499bbd07a0f37e1c9219",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":89},
                    "size":{
                      "width":46,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/硕士模板/u1.png"}},
{
              "id":"d1507a485f6a48cbb8218d98e083e651",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":46,
                  "y":0},
                "size":{
                  "width":127,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c3c3e84f75fa45d6af51c36e5a079e1e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":46,
                      "y":0},
                    "size":{
                      "width":127,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u3.png"}},
{
              "id":"dcfb29a2ccb24d849ecd27f3fc3f5fa9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":46,
                  "y":29},
                "size":{
                  "width":127,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"32f32173214f4b0da60d022f5bce57ca",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1E1E1E,
                      "opacity":1},
                    "location":{
                      "x":46,
                      "y":29},
                    "size":{
                      "width":127,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/招聘信息管理/u14.png"}},
{
              "id":"c4f40122779a4628afc7c9d7715d3944",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":46,
                  "y":89},
                "size":{
                  "width":127,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9b8736b3daa643e191d6f5ed30c8ee87",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":46,
                      "y":89},
                    "size":{
                      "width":127,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/招聘信息管理/u14.png"}},
{
              "id":"a080a277226341d6ab398a8c0d49afe8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":407,
                  "y":0},
                "size":{
                  "width":169,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4c9882d114914ef39e167c8a9eaab714",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":407,
                      "y":0},
                    "size":{
                      "width":169,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u9.png"}},
{
              "id":"ec3f407764bb4478b55b31cf4f75c0f5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":407,
                  "y":29},
                "size":{
                  "width":169,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"83437920f64a48ed940710d165d0e13f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":407,
                      "y":29},
                    "size":{
                      "width":169,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u19.png"}},
{
              "id":"83c4558bd3ed4aeb995f63cab57af6e2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":407,
                  "y":89},
                "size":{
                  "width":169,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d9a69721393642eebcd5fe05020432c4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":407,
                      "y":89},
                    "size":{
                      "width":169,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u19.png"}},
{
              "id":"55a70797a3a94091b1e435c9747f1ac1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":173,
                  "y":0},
                "size":{
                  "width":119,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7aed30bfdba649808682fa5eb4651d46",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":173,
                      "y":0},
                    "size":{
                      "width":119,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u5.png"}},
{
              "id":"852f0b4f4f874bd4b96db38a79ec667b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":173,
                  "y":29},
                "size":{
                  "width":119,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e8a12e9f754e4122a9a260754a60e4e5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":173,
                      "y":29},
                    "size":{
                      "width":119,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/招聘信息管理/u18.png"}},
{
              "id":"88ca9c0cb45e4728b890a5a86019eb0b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":173,
                  "y":89},
                "size":{
                  "width":119,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"18a243e6e54a4bc99a0b1a7100f4a74a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":173,
                      "y":89},
                    "size":{
                      "width":119,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/招聘信息管理/u18.png"}},
{
              "id":"d67001c88be548dbb590f7920050ca28",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":59},
                "size":{
                  "width":46,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d76ad84f89154f6d90dae11e19258d66",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":59},
                    "size":{
                      "width":46,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/硕士模板/u1.png"}},
{
              "id":"b7b7681f759a4cbc9e46dd99c6e37ae7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":46,
                  "y":59},
                "size":{
                  "width":127,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"95a3c2d5367e4069ab8afb2f02fca879",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":46,
                      "y":59},
                    "size":{
                      "width":127,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/招聘信息管理/u14.png"}},
{
              "id":"5d2bf231df6e4a829b4fd530e11addc7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":173,
                  "y":59},
                "size":{
                  "width":119,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"57528631b6fe4cfbbbd265ed26cef88e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":173,
                      "y":59},
                    "size":{
                      "width":119,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/招聘信息管理/u18.png"}},
{
              "id":"66872e4027ab4cdb9e5729d387bd2108",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":407,
                  "y":59},
                "size":{
                  "width":169,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0b745934f51d4d26a0ebf92c09846c9d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":407,
                      "y":59},
                    "size":{
                      "width":169,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u19.png"}},
{
              "id":"86a282405a344be085e70e1c7a82f911",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":149},
                "size":{
                  "width":46,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0c66b0ef1a36423789c5c844a3d4e7aa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":149},
                    "size":{
                      "width":46,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/硕士模板/u21.png"}},
{
              "id":"5127e49793064f24a7446302d4e2be6a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":46,
                  "y":149},
                "size":{
                  "width":127,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f2a9f422fdc84b8cb11f319d9ee46cdc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":46,
                      "y":149},
                    "size":{
                      "width":127,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/招聘信息管理/u112.png"}},
{
              "id":"fbc09b762b33408dac1b93566f338ede",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":173,
                  "y":149},
                "size":{
                  "width":119,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5d8082b3596549d482025fd75c3fc9d6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":173,
                      "y":149},
                    "size":{
                      "width":119,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/招聘信息管理/u116.png"}},
{
              "id":"bd401eeb5df14819bdafe93e22139cb1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":407,
                  "y":149},
                "size":{
                  "width":169,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4df0069d120647b89a42d02f1a9f40cf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":407,
                      "y":149},
                    "size":{
                      "width":169,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u59.png"}},
{
              "id":"87a94a0eb1e647b9980e9927fd5776f5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":119},
                "size":{
                  "width":46,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"793c54ea0e1b474ab81a404bb10ba71e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":119},
                    "size":{
                      "width":46,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/硕士模板/u1.png"}},
{
              "id":"32ef749217c74402a1b3d1daf643ca67",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":46,
                  "y":119},
                "size":{
                  "width":127,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ea67015915014662b0b04dd0949ec63e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":46,
                      "y":119},
                    "size":{
                      "width":127,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/招聘信息管理/u14.png"}},
{
              "id":"45afea8f5e4b4dba9ff3eec5f15ff110",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":173,
                  "y":119},
                "size":{
                  "width":119,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3c9de9e6e38249b2b753eb6b26535668",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":173,
                      "y":119},
                    "size":{
                      "width":119,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/招聘信息管理/u18.png"}},
{
              "id":"c67e21f9e4a246d0916ab8fafed2e02a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":407,
                  "y":119},
                "size":{
                  "width":169,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7d24e531f939477cb9aac6d098e692eb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":407,
                      "y":119},
                    "size":{
                      "width":169,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u19.png"}},
{
              "id":"63f8f594098345069c559c3dd1b04e9e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":292,
                  "y":0},
                "size":{
                  "width":115,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"50ab0882e09441ce9e91e1eea6183a26",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":292,
                      "y":0},
                    "size":{
                      "width":115,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u7.png"}},
{
              "id":"81538492de894fb09619aae648ab17f9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":292,
                  "y":29},
                "size":{
                  "width":115,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"061d6f9bea9b47faab1ed17d04dfd80e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":292,
                      "y":29},
                    "size":{
                      "width":115,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u17.png"}},
{
              "id":"110fda0c551042af9e9f6e6d4023b105",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":292,
                  "y":59},
                "size":{
                  "width":115,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2ab9ff7f83d045f382585745aefae05c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":292,
                      "y":59},
                    "size":{
                      "width":115,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u17.png"}},
{
              "id":"8322ea70922143d99f9fa0376e5e003e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":292,
                  "y":89},
                "size":{
                  "width":115,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"38d11b852f4d48f99075c1e019e4cb6d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":292,
                      "y":89},
                    "size":{
                      "width":115,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u17.png"}},
{
              "id":"649a28a695914e0a952967b825b34441",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":292,
                  "y":119},
                "size":{
                  "width":115,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7b890bf43ab04e05a52faa78dc452f7b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":292,
                      "y":119},
                    "size":{
                      "width":115,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u17.png"}},
{
              "id":"2db66c86fcdd422b937dc7ed82a3a812",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":292,
                  "y":149},
                "size":{
                  "width":115,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bbb066c4cee74d83a0d081a85b438238",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":292,
                      "y":149},
                    "size":{
                      "width":115,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u57.png"}}]},
{
          "id":"78480c0e5eec46c09302c99966fe537a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":126,
              "y":109},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "annotation":{
            "描述":"点击新增按钮，弹出新增页面"}},
{
          "id":"7c23fa50fdb642408022dd5721969b59",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"030ad16089984aab8ee4c9e9409d1f39"},
{
          "id":"2921c62fc4be45f0b5bad6f526887c8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":123,
              "y":64},
            "size":{
              "width":171,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef368232cbdb405cbe96eccfed7cb56d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":123,
                  "y":64},
                "size":{
                  "width":171,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec1e6d70ad3b4984ae6f09fa01a2b5c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontWeight":"700",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":130,
              "y":343},
            "size":{
              "width":222,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1ca3fe1c9094c569264795512ccc905",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontWeight":"700",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":130,
                  "y":343},
                "size":{
                  "width":222,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "030ad16089984aab8ee4c9e9409d1f39":{
      "packageId":"030ad16089984aab8ee4c9e9409d1f39",
      "type":"Axure:Master",
      "name":"人才招聘管理系统后台",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9232e32197a446c6ab3ac4fe47afb413",
            "label":"",
            "type":"menuObject",
            "styleType":"menuObject",
            "visible":true,
            "style":{
              "location":{
                "x":3,
                "y":86},
              "size":{
                "width":94,
                "height":206}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"988f442a183f4ee88509cc6f7639e83e",
                "label":"",
                "type":"table",
                "styleType":"table",
                "visible":true,
                "style":{
                  "fontName":"'应用字体 Regular', '应用字体'",
                  "location":{
                    "x":1,
                    "y":1},
                  "size":{
                    "width":92,
                    "height":204}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"fed27e3024fc4271bf03fd915426fc55",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontName":"'应用字体 Regular', '应用字体'",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "size":{
                        "width":92,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"28425b724562437284c1b3413ebfbc1b",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'应用字体 Regular', '应用字体'",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":92,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 招聘信息管理 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"招聘信息管理.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/招聘信息管理/u148.png"}},
{
                    "id":"7cc6daf02f5846e488a2e43229e8cbdb",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontName":"'应用字体 Regular', '应用字体'",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":40},
                      "size":{
                        "width":92,
                        "height":41}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"34f6be30c9ec4109a5627e1ea10be8a3",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'应用字体 Regular', '应用字体'",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":40},
                          "size":{
                            "width":92,
                            "height":41}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 简历模板管理 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"简历模板管理.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/招聘信息管理/u150.png"}},
{
                    "id":"6beabc4a41534830ae47bf6e5f5ac0cf",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontName":"'应用字体 Regular', '应用字体'",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":81},
                      "size":{
                        "width":92,
                        "height":41}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8dc40013972144dd844af24ead8557cb",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'应用字体 Regular', '应用字体'",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":81},
                          "size":{
                            "width":92,
                            "height":41}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 求职管理 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"求职管理.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/招聘信息管理/u150.png"}},
{
                    "id":"60510bcddbd34329b465172645d875fe",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontName":"'应用字体 Regular', '应用字体'",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":122},
                      "size":{
                        "width":92,
                        "height":41}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"89165b05ac1840c587b8073c47727ae5",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'应用字体 Regular', '应用字体'",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":122},
                          "size":{
                            "width":92,
                            "height":41}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 通知公告 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"通知公告.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/招聘信息管理/u150.png"}},
{
                    "id":"100a2cff887c468f84258eb7cf40101f",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontName":"'应用字体 Regular', '应用字体'",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":163},
                      "size":{
                        "width":92,
                        "height":41}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"fd9868620ceb4fba841cce604260b30c",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'应用字体 Regular', '应用字体'",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":163},
                          "size":{
                            "width":92,
                            "height":41}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 用户管理 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"用户管理.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/招聘信息管理/u156.png"}}]},
{
                "id":"232cc5fe273e448baa605b9679ab1ea8",
                "label":"",
                "type":"menuObject",
                "styleType":"menuObject",
                "visible":true,
                "style":{
                  "location":{
                    "x":93,
                    "y":1},
                  "size":{
                    "width":102,
                    "height":68},
                  "limbo":false},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"99399b02f1d643098b720d4f14369786",
                    "label":"",
                    "type":"table",
                    "styleType":"table",
                    "visible":true,
                    "style":{
                      "fontName":"'应用字体 Regular', '应用字体'",
                      "location":{
                        "x":1,
                        "y":1},
                      "size":{
                        "width":100,
                        "height":66}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8323f9cffe7e4cd08a4ec28dcd3fa16e",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontName":"'应用字体 Regular', '应用字体'",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":100,
                            "height":33},
                          "limbo":false},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"7dfe4ab4347a4ec8b511ac98b57dad5d",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'应用字体 Regular', '应用字体'",
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "size":{
                                "width":100,
                                "height":33},
                              "limbo":false},
                            "adaptiveStyles":{
}}],
                        "interactionMap":{
                          "onClick":{
                            "description":"OnClick",
                            "cases":[{
                                "description":"用例 1",
                                "isNewIfGroup":false,
                                "actions":[{
                                    "action":"linkWindow",
                                    "description":"Open 新增招聘信息 in Current Window",
                                    "target":{
                                      "targetType":"page",
                                      "url":"新增招聘信息.html",
                                      "includeVariables":true},
                                    "linkType":"current"}]}]}},
                        "tabbable":true,
                        "images":{
                          "normal~":"images/招聘信息管理/u160.png"}},
{
                        "id":"c45240286e9d4788aa19b732de47b8ec",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontName":"'应用字体 Regular', '应用字体'",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":33},
                          "size":{
                            "width":100,
                            "height":33},
                          "limbo":false},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"31abfc6f378c42999e2ed0eb20851788",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'应用字体 Regular', '应用字体'",
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "location":{
                                "x":0,
                                "y":33},
                              "size":{
                                "width":100,
                                "height":33},
                              "limbo":false},
                            "adaptiveStyles":{
}}],
                        "interactionMap":{
                          "onClick":{
                            "description":"OnClick",
                            "cases":[{
                                "description":"用例 1",
                                "isNewIfGroup":false,
                                "actions":[{
                                    "action":"linkWindow",
                                    "description":"Open 招聘信息详情 in Current Window",
                                    "target":{
                                      "targetType":"page",
                                      "url":"招聘信息详情.html",
                                      "includeVariables":true},
                                    "linkType":"current"}]}]}},
                        "tabbable":true,
                        "images":{
                          "normal~":"images/招聘信息管理/u162.png"}}]}],
                "parentCellId":"fed27e3024fc4271bf03fd915426fc55"},
{
                "id":"657a840bbdc540a98b516330bc563ca0",
                "label":"",
                "type":"menuObject",
                "styleType":"menuObject",
                "visible":true,
                "style":{
                  "location":{
                    "x":93,
                    "y":82},
                  "size":{
                    "width":102,
                    "height":30},
                  "limbo":false},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"9520925f43104ff19c135876b0a876ee",
                    "label":"",
                    "type":"table",
                    "styleType":"table",
                    "visible":true,
                    "style":{
                      "fontName":"'应用字体 Regular', '应用字体'",
                      "location":{
                        "x":1,
                        "y":1},
                      "size":{
                        "width":100,
                        "height":28}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"dd6a6aa65d7c49c08eaf2897402c1774",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontName":"'应用字体 Regular', '应用字体'",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":100,
                            "height":28},
                          "limbo":false},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"4ca2153f19564050b1b0b79d048af6be",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'应用字体 Regular', '应用字体'",
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "size":{
                                "width":100,
                                "height":28},
                              "limbo":false},
                            "adaptiveStyles":{
}}],
                        "interactionMap":{
                          "onClick":{
                            "description":"OnClick",
                            "cases":[{
                                "description":"用例 1",
                                "isNewIfGroup":false,
                                "actions":[{
                                    "action":"linkWindow",
                                    "description":"Open 求职简历 in Current Window",
                                    "target":{
                                      "targetType":"page",
                                      "url":"求职简历.html",
                                      "includeVariables":true},
                                    "linkType":"current"}]}]}},
                        "tabbable":true,
                        "images":{
                          "normal~":"images/招聘信息管理/u166.png"}}]}],
                "parentCellId":"6beabc4a41534830ae47bf6e5f5ac0cf"}]},
{
            "id":"77952284bd3b4c3697e2e700fa8e9f69",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'应用字体 Regular', '应用字体'",
              "location":{
                "x":10,
                "y":10},
              "size":{
                "width":240,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8605d38b30644110a6b7d7589b917ffe",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'应用字体 Regular', '应用字体'",
                  "location":{
                    "x":10,
                    "y":10},
                  "size":{
                    "width":240,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/人才招聘管理系统后台/u7.png"}},
{
            "id":"52b40107394d4a95973feb78feef7962",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'应用字体 Regular', '应用字体'",
              "location":{
                "x":266,
                "y":12},
              "size":{
                "width":366,
                "height":38}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6d6781c266174d28a530084ef993c2e5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'应用字体 Regular', '应用字体'",
                  "location":{
                    "x":266,
                    "y":12},
                  "size":{
                    "width":366,
                    "height":38}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"de5b16e20ea14d4ca5b691a7d6e768a7",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'应用字体 Regular', '应用字体'",
              "location":{
                "x":970,
                "y":63},
              "size":{
                "width":88,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4b9c250708264d5caf1ddcf8c5b4a78d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'应用字体 Regular', '应用字体'",
                  "location":{
                    "x":970,
                    "y":63},
                  "size":{
                    "width":88,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4e54640567e942f78265fdbc723ce477",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":114,
                "y":80},
              "size":{
                "width":1000,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/人才招聘管理系统后台/u11_line.png"}}]}}},
  "objectPaths":{
    "dc7ab9cfaa5a441ab336d88b41197cb9":{
      "scriptId":"u0"},
    "94f10565a6bb451aa05473d705ea7f81":{
      "scriptId":"u1"},
    "6a7d3e92fa7947fc8ec1765b60a4b38e":{
      "scriptId":"u2"},
    "d1507a485f6a48cbb8218d98e083e651":{
      "scriptId":"u3"},
    "c3c3e84f75fa45d6af51c36e5a079e1e":{
      "scriptId":"u4"},
    "55a70797a3a94091b1e435c9747f1ac1":{
      "scriptId":"u5"},
    "7aed30bfdba649808682fa5eb4651d46":{
      "scriptId":"u6"},
    "63f8f594098345069c559c3dd1b04e9e":{
      "scriptId":"u7"},
    "50ab0882e09441ce9e91e1eea6183a26":{
      "scriptId":"u8"},
    "a080a277226341d6ab398a8c0d49afe8":{
      "scriptId":"u9"},
    "4c9882d114914ef39e167c8a9eaab714":{
      "scriptId":"u10"},
    "b05e61e7350b462d83a3bb2846135aef":{
      "scriptId":"u11"},
    "5de3f5bd86f9435496c52d8fc6d1dc03":{
      "scriptId":"u12"},
    "dcfb29a2ccb24d849ecd27f3fc3f5fa9":{
      "scriptId":"u13"},
    "32f32173214f4b0da60d022f5bce57ca":{
      "scriptId":"u14"},
    "852f0b4f4f874bd4b96db38a79ec667b":{
      "scriptId":"u15"},
    "e8a12e9f754e4122a9a260754a60e4e5":{
      "scriptId":"u16"},
    "81538492de894fb09619aae648ab17f9":{
      "scriptId":"u17"},
    "061d6f9bea9b47faab1ed17d04dfd80e":{
      "scriptId":"u18"},
    "ec3f407764bb4478b55b31cf4f75c0f5":{
      "scriptId":"u19"},
    "83437920f64a48ed940710d165d0e13f":{
      "scriptId":"u20"},
    "d67001c88be548dbb590f7920050ca28":{
      "scriptId":"u21"},
    "d76ad84f89154f6d90dae11e19258d66":{
      "scriptId":"u22"},
    "b7b7681f759a4cbc9e46dd99c6e37ae7":{
      "scriptId":"u23"},
    "95a3c2d5367e4069ab8afb2f02fca879":{
      "scriptId":"u24"},
    "5d2bf231df6e4a829b4fd530e11addc7":{
      "scriptId":"u25"},
    "57528631b6fe4cfbbbd265ed26cef88e":{
      "scriptId":"u26"},
    "110fda0c551042af9e9f6e6d4023b105":{
      "scriptId":"u27"},
    "2ab9ff7f83d045f382585745aefae05c":{
      "scriptId":"u28"},
    "66872e4027ab4cdb9e5729d387bd2108":{
      "scriptId":"u29"},
    "0b745934f51d4d26a0ebf92c09846c9d":{
      "scriptId":"u30"},
    "8956a5877bbd4602b4bac7d7f520420c":{
      "scriptId":"u31"},
    "b22480a1b7a6499bbd07a0f37e1c9219":{
      "scriptId":"u32"},
    "c4f40122779a4628afc7c9d7715d3944":{
      "scriptId":"u33"},
    "9b8736b3daa643e191d6f5ed30c8ee87":{
      "scriptId":"u34"},
    "88ca9c0cb45e4728b890a5a86019eb0b":{
      "scriptId":"u35"},
    "18a243e6e54a4bc99a0b1a7100f4a74a":{
      "scriptId":"u36"},
    "8322ea70922143d99f9fa0376e5e003e":{
      "scriptId":"u37"},
    "38d11b852f4d48f99075c1e019e4cb6d":{
      "scriptId":"u38"},
    "83c4558bd3ed4aeb995f63cab57af6e2":{
      "scriptId":"u39"},
    "d9a69721393642eebcd5fe05020432c4":{
      "scriptId":"u40"},
    "87a94a0eb1e647b9980e9927fd5776f5":{
      "scriptId":"u41"},
    "793c54ea0e1b474ab81a404bb10ba71e":{
      "scriptId":"u42"},
    "32ef749217c74402a1b3d1daf643ca67":{
      "scriptId":"u43"},
    "ea67015915014662b0b04dd0949ec63e":{
      "scriptId":"u44"},
    "45afea8f5e4b4dba9ff3eec5f15ff110":{
      "scriptId":"u45"},
    "3c9de9e6e38249b2b753eb6b26535668":{
      "scriptId":"u46"},
    "649a28a695914e0a952967b825b34441":{
      "scriptId":"u47"},
    "7b890bf43ab04e05a52faa78dc452f7b":{
      "scriptId":"u48"},
    "c67e21f9e4a246d0916ab8fafed2e02a":{
      "scriptId":"u49"},
    "7d24e531f939477cb9aac6d098e692eb":{
      "scriptId":"u50"},
    "86a282405a344be085e70e1c7a82f911":{
      "scriptId":"u51"},
    "0c66b0ef1a36423789c5c844a3d4e7aa":{
      "scriptId":"u52"},
    "5127e49793064f24a7446302d4e2be6a":{
      "scriptId":"u53"},
    "f2a9f422fdc84b8cb11f319d9ee46cdc":{
      "scriptId":"u54"},
    "fbc09b762b33408dac1b93566f338ede":{
      "scriptId":"u55"},
    "5d8082b3596549d482025fd75c3fc9d6":{
      "scriptId":"u56"},
    "2db66c86fcdd422b937dc7ed82a3a812":{
      "scriptId":"u57"},
    "bbb066c4cee74d83a0d081a85b438238":{
      "scriptId":"u58"},
    "bd401eeb5df14819bdafe93e22139cb1":{
      "scriptId":"u59"},
    "4df0069d120647b89a42d02f1a9f40cf":{
      "scriptId":"u60"},
    "78480c0e5eec46c09302c99966fe537a":{
      "scriptId":"u61"},
    "7c23fa50fdb642408022dd5721969b59":{
      "scriptId":"u62",
      "9232e32197a446c6ab3ac4fe47afb413":{
        "scriptId":"u63"},
      "988f442a183f4ee88509cc6f7639e83e":{
        "scriptId":"u64"},
      "fed27e3024fc4271bf03fd915426fc55":{
        "scriptId":"u65"},
      "28425b724562437284c1b3413ebfbc1b":{
        "scriptId":"u66"},
      "7cc6daf02f5846e488a2e43229e8cbdb":{
        "scriptId":"u67"},
      "34f6be30c9ec4109a5627e1ea10be8a3":{
        "scriptId":"u68"},
      "6beabc4a41534830ae47bf6e5f5ac0cf":{
        "scriptId":"u69"},
      "8dc40013972144dd844af24ead8557cb":{
        "scriptId":"u70"},
      "60510bcddbd34329b465172645d875fe":{
        "scriptId":"u71"},
      "89165b05ac1840c587b8073c47727ae5":{
        "scriptId":"u72"},
      "100a2cff887c468f84258eb7cf40101f":{
        "scriptId":"u73"},
      "fd9868620ceb4fba841cce604260b30c":{
        "scriptId":"u74"},
      "232cc5fe273e448baa605b9679ab1ea8":{
        "scriptId":"u75"},
      "99399b02f1d643098b720d4f14369786":{
        "scriptId":"u76"},
      "8323f9cffe7e4cd08a4ec28dcd3fa16e":{
        "scriptId":"u77"},
      "7dfe4ab4347a4ec8b511ac98b57dad5d":{
        "scriptId":"u78"},
      "c45240286e9d4788aa19b732de47b8ec":{
        "scriptId":"u79"},
      "31abfc6f378c42999e2ed0eb20851788":{
        "scriptId":"u80"},
      "657a840bbdc540a98b516330bc563ca0":{
        "scriptId":"u81"},
      "9520925f43104ff19c135876b0a876ee":{
        "scriptId":"u82"},
      "dd6a6aa65d7c49c08eaf2897402c1774":{
        "scriptId":"u83"},
      "4ca2153f19564050b1b0b79d048af6be":{
        "scriptId":"u84"},
      "77952284bd3b4c3697e2e700fa8e9f69":{
        "scriptId":"u85"},
      "8605d38b30644110a6b7d7589b917ffe":{
        "scriptId":"u86"},
      "52b40107394d4a95973feb78feef7962":{
        "scriptId":"u87"},
      "6d6781c266174d28a530084ef993c2e5":{
        "scriptId":"u88"},
      "de5b16e20ea14d4ca5b691a7d6e768a7":{
        "scriptId":"u89"},
      "4b9c250708264d5caf1ddcf8c5b4a78d":{
        "scriptId":"u90"},
      "4e54640567e942f78265fdbc723ce477":{
        "scriptId":"u91"}},
    "2921c62fc4be45f0b5bad6f526887c8a":{
      "scriptId":"u92"},
    "ef368232cbdb405cbe96eccfed7cb56d":{
      "scriptId":"u93"},
    "ec1e6d70ad3b4984ae6f09fa01a2b5c1":{
      "scriptId":"u94"},
    "f1ca3fe1c9094c569264795512ccc905":{
      "scriptId":"u95"}}});