$axure.loadCurrentPage({
  "url":"硕士模板.html",
  "generationDate":new Date(1432187597539.73),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a34360e08cd4416c9bb2836584a31062",
    "type":"Axure:Page",
    "name":"硕士模板",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7d4f8d9a096441169e12f2d9f7dfbe83",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":120,
              "y":150},
            "size":{
              "width":554,
              "height":92}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb71d80e908544a3a61bf220492272f2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":46,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"126e14ce295145dca6b5441395d58845",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":46,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/硕士模板/u1.png"}},
{
              "id":"89c31fb3cb1b41188dcea525ed6397d9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":46,
                  "height":32}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"65ffe87d15464bb6b0e0a7405e7ced6f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":46,
                      "height":32}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/硕士模板/u11.png"}},
{
              "id":"a66e26c252fe4a719e212ada054120cf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":46,
                  "y":0},
                "size":{
                  "width":127,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"53231e4ce1d541018255e1c268cebd50",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":46,
                      "y":0},
                    "size":{
                      "width":127,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/招聘信息管理/u14.png"}},
{
              "id":"f91da243d0db4636b954248e2723b842",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":46,
                  "y":30},
                "size":{
                  "width":127,
                  "height":32}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a4374f2839094dfb85927d29b8998e07",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":46,
                      "y":30},
                    "size":{
                      "width":127,
                      "height":32}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/硕士模板/u13.png"}},
{
              "id":"dd13cb6767e345629351d5d4b038a24b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":310,
                  "y":0},
                "size":{
                  "width":89,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b441dabd61784201ab74601ca055095a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":310,
                      "y":0},
                    "size":{
                      "width":89,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/招聘信息管理/u24.png"}},
{
              "id":"5562409058fe4883a137242781165780",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":310,
                  "y":30},
                "size":{
                  "width":89,
                  "height":32}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b18da6b1cdc340c68dd0e746970fe4a3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":310,
                      "y":30},
                    "size":{
                      "width":89,
                      "height":32}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/硕士模板/u17.png"}},
{
              "id":"3995c8cd301545e588bed88d02e6fc29",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":173,
                  "y":0},
                "size":{
                  "width":137,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"25d8affbd8854dceb655d23c3c2b566c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":173,
                      "y":0},
                    "size":{
                      "width":137,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/招聘信息管理/u22.png"}},
{
              "id":"f4a01dee613540c28092ddf4640a5cc8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":173,
                  "y":30},
                "size":{
                  "width":137,
                  "height":32}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b7f5c15c64054b05b606446058af25a7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":173,
                      "y":30},
                    "size":{
                      "width":137,
                      "height":32}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/硕士模板/u15.png"}},
{
              "id":"5c0cb50e33e249beb0b69dace4976e5b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":399,
                  "y":0},
                "size":{
                  "width":155,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d5d86dfda34544ffb980aa3aeadf2513",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":399,
                      "y":0},
                    "size":{
                      "width":155,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/硕士模板/u9.png"}},
{
              "id":"1fbd75f82e9547db97e3faa5ef608f0f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "underline":true,
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":399,
                  "y":30},
                "size":{
                  "width":155,
                  "height":32}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"537216606c29442281ce070bf84a2525",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "underline":true,
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0066FF,
                      "opacity":1},
                    "location":{
                      "x":399,
                      "y":30},
                    "size":{
                      "width":155,
                      "height":32}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/硕士模板/u19.png"}},
{
              "id":"dad52b1c0bfa4f7b95e0238a06a9b4e1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":62},
                "size":{
                  "width":46,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5390292e8a514fcc87a81e02aa09ff55",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":62},
                    "size":{
                      "width":46,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/硕士模板/u21.png"}},
{
              "id":"51cd8aa07a9146888fe8c07853adfe13",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":46,
                  "y":62},
                "size":{
                  "width":127,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3d78f701291e4d809c3dbe342d9ed5b3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":46,
                      "y":62},
                    "size":{
                      "width":127,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/招聘信息管理/u112.png"}},
{
              "id":"71df405ad77d4453a477bbd65aceee42",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":173,
                  "y":62},
                "size":{
                  "width":137,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0f5133e914f64869a4416c828b1e22ed",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":173,
                      "y":62},
                    "size":{
                      "width":137,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/招聘信息管理/u120.png"}},
{
              "id":"3b13f5a1ab654f579d71dbb749ac3606",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":310,
                  "y":62},
                "size":{
                  "width":89,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b3c6fd04f2064d92ad7237d5d78c4521",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":310,
                      "y":62},
                    "size":{
                      "width":89,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/招聘信息管理/u122.png"}},
{
              "id":"4d43e9cef77c4f8ba2c5b2d98838d119",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "underline":true,
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":399,
                  "y":62},
                "size":{
                  "width":155,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ac39e006f82a4eda9752beee9f98cfd8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "underline":true,
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0066FF,
                      "opacity":1},
                    "location":{
                      "x":399,
                      "y":62},
                    "size":{
                      "width":155,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/硕士模板/u29.png"}}]},
{
          "id":"03c78154f3bd40a688ef393311cb9bea",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":240,
              "y":110},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 硕士基础模板 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"硕士基础模板.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"db3eb1e097d640bca2fad90b1709c3e3",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"030ad16089984aab8ee4c9e9409d1f39"},
{
          "id":"13d6dd23d9864032ab6fc594b6ce9bae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":123,
              "y":64},
            "size":{
              "width":171,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"210b3f43169f4354999a1e1add48d698",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":123,
                  "y":64},
                "size":{
                  "width":171,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38f7ac048eef42adaf59ec6160c418e7",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":360,
              "y":110},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 硕士基础模板 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"硕士基础模板.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"3b81aeee7d724e19af70264a85b2ba58",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":120,
              "y":110},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 新增扩展项 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"新增扩展项.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
    "030ad16089984aab8ee4c9e9409d1f39":{
      "packageId":"030ad16089984aab8ee4c9e9409d1f39",
      "type":"Axure:Master",
      "name":"人才招聘管理系统后台",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9232e32197a446c6ab3ac4fe47afb413",
            "label":"",
            "type":"menuObject",
            "styleType":"menuObject",
            "visible":true,
            "style":{
              "location":{
                "x":3,
                "y":86},
              "size":{
                "width":94,
                "height":206}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"988f442a183f4ee88509cc6f7639e83e",
                "label":"",
                "type":"table",
                "styleType":"table",
                "visible":true,
                "style":{
                  "fontName":"'应用字体 Regular', '应用字体'",
                  "location":{
                    "x":1,
                    "y":1},
                  "size":{
                    "width":92,
                    "height":204}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"fed27e3024fc4271bf03fd915426fc55",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontName":"'应用字体 Regular', '应用字体'",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "size":{
                        "width":92,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"28425b724562437284c1b3413ebfbc1b",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'应用字体 Regular', '应用字体'",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":92,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 招聘信息管理 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"招聘信息管理.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/招聘信息管理/u148.png"}},
{
                    "id":"7cc6daf02f5846e488a2e43229e8cbdb",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontName":"'应用字体 Regular', '应用字体'",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":40},
                      "size":{
                        "width":92,
                        "height":41}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"34f6be30c9ec4109a5627e1ea10be8a3",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'应用字体 Regular', '应用字体'",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":40},
                          "size":{
                            "width":92,
                            "height":41}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 简历模板管理 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"简历模板管理.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/招聘信息管理/u150.png"}},
{
                    "id":"6beabc4a41534830ae47bf6e5f5ac0cf",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontName":"'应用字体 Regular', '应用字体'",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":81},
                      "size":{
                        "width":92,
                        "height":41}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8dc40013972144dd844af24ead8557cb",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'应用字体 Regular', '应用字体'",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":81},
                          "size":{
                            "width":92,
                            "height":41}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 求职管理 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"求职管理.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/招聘信息管理/u150.png"}},
{
                    "id":"60510bcddbd34329b465172645d875fe",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontName":"'应用字体 Regular', '应用字体'",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":122},
                      "size":{
                        "width":92,
                        "height":41}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"89165b05ac1840c587b8073c47727ae5",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'应用字体 Regular', '应用字体'",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":122},
                          "size":{
                            "width":92,
                            "height":41}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 通知公告 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"通知公告.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/招聘信息管理/u150.png"}},
{
                    "id":"100a2cff887c468f84258eb7cf40101f",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontName":"'应用字体 Regular', '应用字体'",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":163},
                      "size":{
                        "width":92,
                        "height":41}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"fd9868620ceb4fba841cce604260b30c",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'应用字体 Regular', '应用字体'",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":163},
                          "size":{
                            "width":92,
                            "height":41}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 用户管理 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"用户管理.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/招聘信息管理/u156.png"}}]},
{
                "id":"232cc5fe273e448baa605b9679ab1ea8",
                "label":"",
                "type":"menuObject",
                "styleType":"menuObject",
                "visible":true,
                "style":{
                  "location":{
                    "x":93,
                    "y":1},
                  "size":{
                    "width":102,
                    "height":68},
                  "limbo":false},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"99399b02f1d643098b720d4f14369786",
                    "label":"",
                    "type":"table",
                    "styleType":"table",
                    "visible":true,
                    "style":{
                      "fontName":"'应用字体 Regular', '应用字体'",
                      "location":{
                        "x":1,
                        "y":1},
                      "size":{
                        "width":100,
                        "height":66}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8323f9cffe7e4cd08a4ec28dcd3fa16e",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontName":"'应用字体 Regular', '应用字体'",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":100,
                            "height":33},
                          "limbo":false},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"7dfe4ab4347a4ec8b511ac98b57dad5d",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'应用字体 Regular', '应用字体'",
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "size":{
                                "width":100,
                                "height":33},
                              "limbo":false},
                            "adaptiveStyles":{
}}],
                        "interactionMap":{
                          "onClick":{
                            "description":"OnClick",
                            "cases":[{
                                "description":"用例 1",
                                "isNewIfGroup":false,
                                "actions":[{
                                    "action":"linkWindow",
                                    "description":"Open 新增招聘信息 in Current Window",
                                    "target":{
                                      "targetType":"page",
                                      "url":"新增招聘信息.html",
                                      "includeVariables":true},
                                    "linkType":"current"}]}]}},
                        "tabbable":true,
                        "images":{
                          "normal~":"images/招聘信息管理/u160.png"}},
{
                        "id":"c45240286e9d4788aa19b732de47b8ec",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontName":"'应用字体 Regular', '应用字体'",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":33},
                          "size":{
                            "width":100,
                            "height":33},
                          "limbo":false},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"31abfc6f378c42999e2ed0eb20851788",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'应用字体 Regular', '应用字体'",
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "location":{
                                "x":0,
                                "y":33},
                              "size":{
                                "width":100,
                                "height":33},
                              "limbo":false},
                            "adaptiveStyles":{
}}],
                        "interactionMap":{
                          "onClick":{
                            "description":"OnClick",
                            "cases":[{
                                "description":"用例 1",
                                "isNewIfGroup":false,
                                "actions":[{
                                    "action":"linkWindow",
                                    "description":"Open 招聘信息详情 in Current Window",
                                    "target":{
                                      "targetType":"page",
                                      "url":"招聘信息详情.html",
                                      "includeVariables":true},
                                    "linkType":"current"}]}]}},
                        "tabbable":true,
                        "images":{
                          "normal~":"images/招聘信息管理/u162.png"}}]}],
                "parentCellId":"fed27e3024fc4271bf03fd915426fc55"},
{
                "id":"657a840bbdc540a98b516330bc563ca0",
                "label":"",
                "type":"menuObject",
                "styleType":"menuObject",
                "visible":true,
                "style":{
                  "location":{
                    "x":93,
                    "y":82},
                  "size":{
                    "width":102,
                    "height":30},
                  "limbo":false},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"9520925f43104ff19c135876b0a876ee",
                    "label":"",
                    "type":"table",
                    "styleType":"table",
                    "visible":true,
                    "style":{
                      "fontName":"'应用字体 Regular', '应用字体'",
                      "location":{
                        "x":1,
                        "y":1},
                      "size":{
                        "width":100,
                        "height":28}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"dd6a6aa65d7c49c08eaf2897402c1774",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontName":"'应用字体 Regular', '应用字体'",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":100,
                            "height":28},
                          "limbo":false},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"4ca2153f19564050b1b0b79d048af6be",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'应用字体 Regular', '应用字体'",
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "size":{
                                "width":100,
                                "height":28},
                              "limbo":false},
                            "adaptiveStyles":{
}}],
                        "interactionMap":{
                          "onClick":{
                            "description":"OnClick",
                            "cases":[{
                                "description":"用例 1",
                                "isNewIfGroup":false,
                                "actions":[{
                                    "action":"linkWindow",
                                    "description":"Open 求职简历 in Current Window",
                                    "target":{
                                      "targetType":"page",
                                      "url":"求职简历.html",
                                      "includeVariables":true},
                                    "linkType":"current"}]}]}},
                        "tabbable":true,
                        "images":{
                          "normal~":"images/招聘信息管理/u166.png"}}]}],
                "parentCellId":"6beabc4a41534830ae47bf6e5f5ac0cf"}]},
{
            "id":"77952284bd3b4c3697e2e700fa8e9f69",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'应用字体 Regular', '应用字体'",
              "location":{
                "x":10,
                "y":10},
              "size":{
                "width":240,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8605d38b30644110a6b7d7589b917ffe",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'应用字体 Regular', '应用字体'",
                  "location":{
                    "x":10,
                    "y":10},
                  "size":{
                    "width":240,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/人才招聘管理系统后台/u7.png"}},
{
            "id":"52b40107394d4a95973feb78feef7962",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'应用字体 Regular', '应用字体'",
              "location":{
                "x":266,
                "y":12},
              "size":{
                "width":366,
                "height":38}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6d6781c266174d28a530084ef993c2e5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'应用字体 Regular', '应用字体'",
                  "location":{
                    "x":266,
                    "y":12},
                  "size":{
                    "width":366,
                    "height":38}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"de5b16e20ea14d4ca5b691a7d6e768a7",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'应用字体 Regular', '应用字体'",
              "location":{
                "x":970,
                "y":63},
              "size":{
                "width":88,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4b9c250708264d5caf1ddcf8c5b4a78d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'应用字体 Regular', '应用字体'",
                  "location":{
                    "x":970,
                    "y":63},
                  "size":{
                    "width":88,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4e54640567e942f78265fdbc723ce477",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":114,
                "y":80},
              "size":{
                "width":1000,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/人才招聘管理系统后台/u11_line.png"}}]}}},
  "objectPaths":{
    "7d4f8d9a096441169e12f2d9f7dfbe83":{
      "scriptId":"u0"},
    "bb71d80e908544a3a61bf220492272f2":{
      "scriptId":"u1"},
    "126e14ce295145dca6b5441395d58845":{
      "scriptId":"u2"},
    "a66e26c252fe4a719e212ada054120cf":{
      "scriptId":"u3"},
    "53231e4ce1d541018255e1c268cebd50":{
      "scriptId":"u4"},
    "3995c8cd301545e588bed88d02e6fc29":{
      "scriptId":"u5"},
    "25d8affbd8854dceb655d23c3c2b566c":{
      "scriptId":"u6"},
    "dd13cb6767e345629351d5d4b038a24b":{
      "scriptId":"u7"},
    "b441dabd61784201ab74601ca055095a":{
      "scriptId":"u8"},
    "5c0cb50e33e249beb0b69dace4976e5b":{
      "scriptId":"u9"},
    "d5d86dfda34544ffb980aa3aeadf2513":{
      "scriptId":"u10"},
    "89c31fb3cb1b41188dcea525ed6397d9":{
      "scriptId":"u11"},
    "65ffe87d15464bb6b0e0a7405e7ced6f":{
      "scriptId":"u12"},
    "f91da243d0db4636b954248e2723b842":{
      "scriptId":"u13"},
    "a4374f2839094dfb85927d29b8998e07":{
      "scriptId":"u14"},
    "f4a01dee613540c28092ddf4640a5cc8":{
      "scriptId":"u15"},
    "b7f5c15c64054b05b606446058af25a7":{
      "scriptId":"u16"},
    "5562409058fe4883a137242781165780":{
      "scriptId":"u17"},
    "b18da6b1cdc340c68dd0e746970fe4a3":{
      "scriptId":"u18"},
    "1fbd75f82e9547db97e3faa5ef608f0f":{
      "scriptId":"u19"},
    "537216606c29442281ce070bf84a2525":{
      "scriptId":"u20"},
    "dad52b1c0bfa4f7b95e0238a06a9b4e1":{
      "scriptId":"u21"},
    "5390292e8a514fcc87a81e02aa09ff55":{
      "scriptId":"u22"},
    "51cd8aa07a9146888fe8c07853adfe13":{
      "scriptId":"u23"},
    "3d78f701291e4d809c3dbe342d9ed5b3":{
      "scriptId":"u24"},
    "71df405ad77d4453a477bbd65aceee42":{
      "scriptId":"u25"},
    "0f5133e914f64869a4416c828b1e22ed":{
      "scriptId":"u26"},
    "3b13f5a1ab654f579d71dbb749ac3606":{
      "scriptId":"u27"},
    "b3c6fd04f2064d92ad7237d5d78c4521":{
      "scriptId":"u28"},
    "4d43e9cef77c4f8ba2c5b2d98838d119":{
      "scriptId":"u29"},
    "ac39e006f82a4eda9752beee9f98cfd8":{
      "scriptId":"u30"},
    "03c78154f3bd40a688ef393311cb9bea":{
      "scriptId":"u31"},
    "db3eb1e097d640bca2fad90b1709c3e3":{
      "scriptId":"u32",
      "9232e32197a446c6ab3ac4fe47afb413":{
        "scriptId":"u33"},
      "988f442a183f4ee88509cc6f7639e83e":{
        "scriptId":"u34"},
      "fed27e3024fc4271bf03fd915426fc55":{
        "scriptId":"u35"},
      "28425b724562437284c1b3413ebfbc1b":{
        "scriptId":"u36"},
      "7cc6daf02f5846e488a2e43229e8cbdb":{
        "scriptId":"u37"},
      "34f6be30c9ec4109a5627e1ea10be8a3":{
        "scriptId":"u38"},
      "6beabc4a41534830ae47bf6e5f5ac0cf":{
        "scriptId":"u39"},
      "8dc40013972144dd844af24ead8557cb":{
        "scriptId":"u40"},
      "60510bcddbd34329b465172645d875fe":{
        "scriptId":"u41"},
      "89165b05ac1840c587b8073c47727ae5":{
        "scriptId":"u42"},
      "100a2cff887c468f84258eb7cf40101f":{
        "scriptId":"u43"},
      "fd9868620ceb4fba841cce604260b30c":{
        "scriptId":"u44"},
      "232cc5fe273e448baa605b9679ab1ea8":{
        "scriptId":"u45"},
      "99399b02f1d643098b720d4f14369786":{
        "scriptId":"u46"},
      "8323f9cffe7e4cd08a4ec28dcd3fa16e":{
        "scriptId":"u47"},
      "7dfe4ab4347a4ec8b511ac98b57dad5d":{
        "scriptId":"u48"},
      "c45240286e9d4788aa19b732de47b8ec":{
        "scriptId":"u49"},
      "31abfc6f378c42999e2ed0eb20851788":{
        "scriptId":"u50"},
      "657a840bbdc540a98b516330bc563ca0":{
        "scriptId":"u51"},
      "9520925f43104ff19c135876b0a876ee":{
        "scriptId":"u52"},
      "dd6a6aa65d7c49c08eaf2897402c1774":{
        "scriptId":"u53"},
      "4ca2153f19564050b1b0b79d048af6be":{
        "scriptId":"u54"},
      "77952284bd3b4c3697e2e700fa8e9f69":{
        "scriptId":"u55"},
      "8605d38b30644110a6b7d7589b917ffe":{
        "scriptId":"u56"},
      "52b40107394d4a95973feb78feef7962":{
        "scriptId":"u57"},
      "6d6781c266174d28a530084ef993c2e5":{
        "scriptId":"u58"},
      "de5b16e20ea14d4ca5b691a7d6e768a7":{
        "scriptId":"u59"},
      "4b9c250708264d5caf1ddcf8c5b4a78d":{
        "scriptId":"u60"},
      "4e54640567e942f78265fdbc723ce477":{
        "scriptId":"u61"}},
    "13d6dd23d9864032ab6fc594b6ce9bae":{
      "scriptId":"u62"},
    "210b3f43169f4354999a1e1add48d698":{
      "scriptId":"u63"},
    "38f7ac048eef42adaf59ec6160c418e7":{
      "scriptId":"u64"},
    "3b81aeee7d724e19af70264a85b2ba58":{
      "scriptId":"u65"}}});